# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dblab < Formula
  desc "A CLI tool for practicing real-world debugging skills"
  homepage "https://github.com/Lokesh-Kudipudi/DebugLab"
  version "1.0.6"

  on_macos do
    on_intel do
      url "https://github.com/Lokesh-Kudipudi/DebugLab/releases/download/v1.0.6/DebugLab_Darwin_x86_64.tar.gz"
      sha256 "7464f6b62242e2fed691faa7c7442911dec7ea9e23b43055dec312ae7d64194a"

      def install
        bin.install "dblab"
      end
    end
    on_arm do
      url "https://github.com/Lokesh-Kudipudi/DebugLab/releases/download/v1.0.6/DebugLab_Darwin_arm64.tar.gz"
      sha256 "27483f61cd84d6f1125104af8684dcb4369219176df481912730a276e4b7f9ac"

      def install
        bin.install "dblab"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lokesh-Kudipudi/DebugLab/releases/download/v1.0.6/DebugLab_Linux_x86_64.tar.gz"
        sha256 "6cb04ec5ca99eb6ae9f78067b810f77c602973622e0306f07475f154a939df3d"

        def install
          bin.install "dblab"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lokesh-Kudipudi/DebugLab/releases/download/v1.0.6/DebugLab_Linux_arm64.tar.gz"
        sha256 "357c252d311ee188cd13ab67301f089f5b735656b78433e44fe3b17565f34dd7"

        def install
          bin.install "dblab"
        end
      end
    end
  end

  test do
    system "#{bin}/dblab help"
  end
end
