# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dblab < Formula
  desc "A CLI tool for practicing real-world debugging skills"
  homepage "https://github.com/Lokesh-Kudipudi/DebugLab"
  version "1.0.7"

  on_macos do
    on_intel do
      url "https://github.com/Lokesh-Kudipudi/DebugLab/releases/download/v1.0.7/DebugLab_Darwin_x86_64.tar.gz"
      sha256 "a2f34bf5fae465a90805ccfe2405daf78cc92d8b85fcb60b27ffcfc9e672f2bd"

      def install
        bin.install "dblab"
      end
    end
    on_arm do
      url "https://github.com/Lokesh-Kudipudi/DebugLab/releases/download/v1.0.7/DebugLab_Darwin_arm64.tar.gz"
      sha256 "8fafb4d44a46735381fcb65eb57c291c4a09e0551a5cd3d857874329d832f7bd"

      def install
        bin.install "dblab"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lokesh-Kudipudi/DebugLab/releases/download/v1.0.7/DebugLab_Linux_x86_64.tar.gz"
        sha256 "447a75c3401f97d7019b85a4af3fc83f8b74cc9b3e4b020cec2072e188382efc"

        def install
          bin.install "dblab"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lokesh-Kudipudi/DebugLab/releases/download/v1.0.7/DebugLab_Linux_arm64.tar.gz"
        sha256 "857241fa453de6aa92e57635d5db079456cca44c36d21aba09135e22263f421c"

        def install
          bin.install "dblab"
        end
      end
    end
  end

  test do
    system "#{bin}/dblab help"
  end
end
